### ISSUE TITLE
Missing migration

### ISSUE THREAD

**Issue by ikonitas** [ImperialCollegeLondon/django-drf-filepond#13] opened 2019-08-02 15:51 UTC
Please can we add the missing migration for this package:

```
└─[16:45]$ ./manage.py makemigrations
Raven is not configured (logging is disabled). Please see the documentation for more information.
Migrations for 'django_drf_filepond':
  /private/var/envs/samaritansselfhelp/lib/python3.7/site-packages/django_drf_filepond/migrations/0004_auto_20190802_1645.py
    - Alter field file on temporaryupload
    - Alter field file_id on temporaryupload
```

**Comment by jcohen02** [comment] 2019-08-03 17:33
Hi @ikonitas, thanks for highlighting this. It's now fixed and a new release [v0.1.1](https://github.com/ImperialCollegeLondon/django-drf-filepond/releases/tag/v0.1.1) has been created.

**Comment by ikonitas** [comment] 2019-08-13 10:57
@jcohen02 thanks for this, but there is another issue with your migrations:
Your `upload_to` is dynamic and every time I change it will create new migration please take a look at https://stackoverflow.com/questions/30624319/django-1-8-fails-migration-with-dynamic-upload-to-over-a-filefield

**Comment by jcohen02** [comment] 2019-08-16 10:23
@ikonitas I've updated the `FileField`'s `upload_to` attribute to point to a deconstructible class as detailed at the link you provided (thanks for the pointer), however, it looks like it might actually be the `storage` attribute that is causing the issue here.

I've created a test app and I can reproduce the issue of `makemigrations` generating a new migration the first time I run it. 

The new migration that is created seems to be related to the path that is created by `os.path.join(local_settings.BASE_DIR,'filepond_uploads')` being different to the default path set for the `FileSystemStorage` object of `/tmp/filepond_uploads` ([see here](https://github.com/ImperialCollegeLondon/django-drf-filepond/blob/908bc740c56c76d933de0784ef4d39fbe14ef3b3/django_drf_filepond/migrations/0004_tempupload_mods.py#L19)). If I manually modify migration 0004 to set the path in the storage parameter to the actual filesystem location that `os.path.join(local_settings.BASE_DIR,'filepond_uploads')` expands to, then no new migration is created.

I'm a little unsure what is causing this since this seems to have been discussed in this [rather old Django issue](https://code.djangoproject.com/ticket/22337) where the suggestion is that the storage location has no issue on the database and therefore shouldn't be part of the `FileField`'s deconstruct implementation. As far as I can see, this was resolved some time ago.

You say above "every time I change it will create a new migration" - are you seeing this happen multiple times? Or only when, say, you update to a new version of the `django-drf-filepond` library? I only see a new migration created once. If I update the models in my test app, new migrations are created for them but nothing additional is created for `django_drf_filepond`.

Hope this makes sense, I'm continuing to investigate but let me know if I've misunderstood the issue you're seeing.

**Comment by rob-barber** [comment] 2019-09-04 00:39
I took the time to fix the issue. I've issued a pull request for the fix.

Essentially, a subclass of FileSystemStorage needed to be created so that instead of using the "location" parameter in the initializer (i.e. FileSystemStorage(location="blah/")) the location kwarg is set within the subclass's initializer. In this way the Django migrations no longer use hard coded paths but the sub-classed FileSystemStorage name instead. This prevents changes of the tmp_uploads path within each project's settings from being recognized as changes to the migration system.

**Closed** 2019-09-06 17:20 UTC
Labels: bug
