### ISSUE TITLE
Is it possible to use libraries like boto or django-storages?

### ISSUE THREAD

**Issue by casoetan** [ImperialCollegeLondon/django-drf-filepond#6] opened 2019-03-25 01:53 UTC
This is to upload to something like AWS or Google Storage

**Comment by jcohen02** [comment] 2019-03-25 11:16
@casoetan, can you explain a little more about the use case you have in mind here?

Would you be looking for the temporary file upload to be stored within a cloud storage service such as S3 or Google Cloud Storage? Or this would only be a requirement for permanent storage of a file?

There's no support for anything like this at present but it could certainly be added. If you wanted the temporary upload to be stored in cloud storage, I guess the most straightforward approach, initially at least, would be for the file to be uploaded to the `django-drf-filepond` app and then sent from there to the relevant cloud storage service. (i.e. there would be no direct upload to the cloud service from the client web application). However, I can see some potential issues here.

I guess you'd want to wait for the upload to the cloud storage to complete successfully before sending a confirmation back to the client. The filepond front-end will show the upload as being 100% complete once all the data has been sent to the Django app but there could then be a delay (depending on the size of the upload) while the data is sent to the remote storage service.

An alternative might be to send the data to the cloud storage asynchronously, caching a copy on the Django server which is then retained if upload to the cloud storage fails.

This would need some further thought - there may be some other issues to consider here. 

Either way, was this the sort of thing you were looking for?

**Comment by casoetan** [comment] 2019-03-26 00:37
Yes. That's pretty close, the choice of doing it either way would be awesome. 

Also, thinking further, having the ability to use any cloud storage library like [django-storages](https://django-storages.readthedocs.io/en/latest/) to manage upload to the cloud automatically will be a plus. What do you think?

**Comment by jcohen02** [comment] 2019-03-26 20:02
This is certainly something that it would be nice to have. I guess the options here are either to have some sort of pluggable setup with an interface against which you write your own connector to push files to the storage of your choice, or something more comprehensive within `django-drf-filepond` that provides built in support for specific cloud storage backends.

I'll give this some more thought, it's not something I think I'll be able to add in right away but it would be good to add to the feature list.

**Comment by casoetan** [comment] 2019-03-27 01:35
The pluggable interface I sounds great to me. You won't have to reinvent cloud uploads and users can just plugin whatever storage engine they use

**Comment by 3to1null** [comment] 2019-08-12 09:31
Hi! I was wondering if there was any progress on this? Is it already possible to hack something together maybe? I only need the permanent storage to be on a different server (using `django-storages`) but I also need to use the load function, so just copying it won't work.

**Comment by jcohen02** [comment] 2019-08-12 19:34
Hi @3to1null, I'm hoping to get something in place to support this, even if just an initial prototype, within the next few days.

When you say you need the storage to be on a different server, which django-storages backend would you be wanting to use? Would this be [SFTP](https://django-storages.readthedocs.io/en/latest/backends/sftp.html)?

I'm hoping to get something in place to support cloud-based remote storage too, as requested by @casoetan, however, I wonder if trying something like SFTP in the initial prototype might be a good way to get started with this feature.

**Comment by 3to1null** [comment] 2019-08-13 07:42
I am using [Min.io](https://min.io/) coupled with the `storages.backends.s3boto3.S3Boto3Storage` backend (Minio is pretty much a local AWS S3 instance). However, since the tool I'm developing is for internal use only I figured it would be easier to just create my own quick & dirty file upload.

If you want to add support for different types of storages, I would suggest to do this either with a general API or using the `default-storage` component in Django, instead of adding it specifically for one type of storage. Of course I'm not familiar with your code, so this might not be possible.

**Comment by pasevin** [comment] 2019-09-02 21:32
This would be a life saver! Can't wait for the update :) Thanks for your work!

**Comment by jcohen02** [comment] 2019-09-03 08:40
Hi @pasevin, pleased to say that the development of this feature is now almost complete and it should be going live this week. The code is available in the [feature/storage](https://github.com/ImperialCollegeLondon/django-drf-filepond/tree/feature/storage) branch and the docs in that branch have been updated with details of configuration for the new feature if you'd like to take a look.

**Comment by jcohen02** [comment] 2019-09-03 08:55
The implementation of the new storage feature makes use of [django-storages](https://django-storages.readthedocs.io/en/latest/) so S3 will be supported on release (been testing against [MinIO](https://github.com/minio/minio)).

At present, the implementation assumes that temporary uploads will first be stored in some temporary space on the host server and then when the upload is confirmed, they are moved to permanent storage using the `django_drf_filepond.api.store_upload` function.

@pasevin does this support your use case? 

The next enhancement is to use remote storage for temporary uploads and send uploaded data directly to some designated temporary storage location on the remote file store. However, this could present issues if the transfer to the remote file store fails - does the uploaded data get dropped altogether? Should it be cached on the host server? The response to the client initiating the upload shouldn't be delayed by any performance issues with transferring the data to the remote file store.

**Comment by pasevin** [comment] 2019-09-19 08:53
@jcohen02 Thanks for your hard work. I'm currently working on the other part of my project, but as soon as I come back to filepond integration, I will dig in deeper.

I'm already using django-storages, so I think there will be no issues.

It makes sense to firstly store files in some temp directory. The only issue with that is what happens if server runs out of space. Will the library return some kind of response?

**Comment by jcohen02** [comment] 2019-09-20 10:43
Thanks all for the input on this issue, [v0.2.0rc1](https://github.com/ImperialCollegeLondon/django-drf-filepond/releases/tag/v0.2.0rc1) has just been released with *django-storages* support and significant new documentation including a more advanced tutorial with code samples for use of the remote storage functionality. It's on [PyPi as a pre-release](https://pypi.org/project/django-drf-filepond/0.2.0rc1/) too.

Hoping to progress this to a full stable release within the next week or so but would be good to get some feedback on whether this is working for you and providing the functionality you want.

**Comment by jcohen02** [comment] 2020-04-28 15:13
django-storages support has been included within django-drf-filepond for some time now so I'm closing this issue.

**Closed by jcohen02** 2020-04-28 15:13 UTC
Labels: enhancement
